# This is a basic workflow to help you get started with Actions

name: Custom Workflow name

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main2" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"



  # This workflow contains a single job called "build"
  test-env-echo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "$CI"
          echo "$GITHUB_ACTION"
          echo "$GITHUB_ACTION_PATH"
          echo "$GITHUB_ACTION_REPOSITORY"
          echo "$GITHUB_ACTION_REPOSITORY"
          echo "$GITHUB_ACTOR"
          echo "$GITHUB_API_URL"
          echo "$GITHUB_BASE_REF"
          echo "$GITHUB_ENV"
          echo "$GITHUB_EVENT_NAME"
          echo "$GITHUB_EVENT_PATH"
          echo "$GITHUB_JOB"
          echo "$GITHUB_JOB"
          echo "$GITHUB_PATH"
          echo "$GITHUB_WORKFLOW"
          echo "$RUNNER_ARCH"
          echo "$RUNNER_NAME"
          echo "$RUNNER_OS"
          echo "$RUNNER_TEMP"

      - name: Dump GitHub context
        env:
          TEST_STEP_LEVEL_VAR: www222
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"