name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REPOSITORY: ghcr.io
  IMAGE_TAG: ${{ github.run_number }}
#  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: terbooter/try-actions

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "$IMAGE_NAME:$IMAGE_TAG"

    - name: List docker images
      run: docker image ls

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
