name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_REPOSITORY: ghcr.io
  IMAGE_TAG: ${{ github.run_number }}
  IMAGE_NAME: ${{ github.repository }}


jobs:

  build:

    env:
      FULL_IMAGE_NAME: ${{ env.DOCKER_REPOSITORY}}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Print Info
      run: |
        echo "$IMAGE_NAME"
        echo "$FULL_IMAGE_NAME"


    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "$FULL_IMAGE_NAME"

    - name: List docker images
      run: docker image ls

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REPOSITORY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Github Registry
      run: docker push "$FULL_IMAGE_NAME"
