name: Docker Image CI

on:
  push:
    branches: [ "main2" ]
  pull_request:
    branches: [ "main2" ]

env:
  DOCKER_REPOSITORY: ghcr.io
  IMAGE_TAG: ${{ github.run_number }}
  IMAGE_NAME: ${{ github.repository }}

  FULL_IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.run_number }}

jobs:

  build:

    env:
      TEST_VAR: ${{ env }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Print Info
      run: |
        echo "$IMAGE_NAME"
        echo "$FULL_IMAGE_NAME"


    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "$FULL_IMAGE_NAME"

    - name: List docker images
      run: docker image ls

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Github Registry
      run: docker push "$FULL_IMAGE_NAME"
